swagger: "2.0"
info:
  title: Events
  description: Example service
  version: 0.0.1

definitions:
  ErrorTest:
    type: object
    required:
      - message
      - code
    description: Error message
    properties:
      message:
        x-type: string
      code:
        x-type: integer

  HealthCheck:
    type: object
    required:
      - message
    properties:
      message:
        type: string
