definitions:
  ErrorTest:
    type: object
    required:
      - message
      - code
    description: Error message
    properties:
      message:
        x-type: string
      code:
        x-type: integer

  HealthCheck:
    type: object
    required:
      - message
    properties:
      message:
        type: string
