swagger: "2.0"
info:
  title: Example service
  description: Example service
  version: 0.0.1
host: localhost
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json

paths:
  /health:
    get:
      operationId: HealthCheck
      description: Health check
      responses:
        200:
          description: successful response
          schema:
            $ref: '#/definitions/HealthCheck'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

definitions:
  ErrorTest:
    type: object
    required:
      - message
      - code
    description: Error message
    properties:
      message:
        x-type: string
      code:
        x-type: integer

  HealthCheck:
    type: object
    required:
      - message
    properties:
      message:
        type: string
